### ISSUE TITLE
Make it as Software as a Service

### ISSUE THREAD

**Issue by georgringer** [andygrunwald/Jacobine#11]
It would be awesome if that tool would be like metrics.typo3.org which just crawls and puts out the results.

I would love to use something for https://git.typo3.org/TYPO3CMS/Extensions/news.git ;)

**Comment by andygrunwald** [comment]
This is still a good idea. But i won't continue Jacobine in the current way.
I am still interested in the whole topic, but won`t put to much effort in the current system.
I learned a lot and will focus on a different topics and when i come back to such a topic i will put this online in a new way.
This ticket will be closed to cleanup the project and to focus on new ideas for 2016 :tada:
