### ISSUE TITLE
Generate user statistis

### ISSUE THREAD

**Issue by georgringer** [andygrunwald/Jacobine#12]
do you know http://resume.github.io/?georgringer

I guess something like that would be "quite" simple to use, especially as the code behind is public as well

**Comment by andygrunwald** [comment]
This is still a good idea. But i won't continue Jacobine in the current way.
I am still interested in the whole topic, but won`t put to much effort in the current system.
I learned a lot and will focus on a different topics and when i come back to such a topic i will put this online in a new way.
This ticket will be closed to cleanup the project and to focus on new ideas for 2016 :tada:
